[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Optional: pretty URLs
[[redirects]]
  from = "/upload"
  to = "/upload.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-reviews.html"
  status = 200
